"""Helpers shared by the code generators in tools/gen_*.py."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

HEADER = "// GENERATED by tools/{tool} from {src} — do not edit by hand.\n// Regenerate: ./build.ps1 -Gen"


def pascal(name: str) -> str:
    """'bg.base' / 'caption-close' / 'bodyStrong' -> 'BgBase' / 'CaptionClose' / 'BodyStrong'."""
    parts = re.split(r"[.\-_ ]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def cpp_float(v) -> str:
    """16 -> '16.0f', 0.22 -> '0.22f' (a bare '16f' is not valid C++)."""
    s = f"{float(v):g}"
    return (s if any(c in s for c in ".e") else s + ".0") + "f"


def cpp_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_if_changed(path: Path, text: str) -> bool:
    """Write only when content differs so incremental builds are not invalidated needlessly."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        print(f"up to date  {path.relative_to(ROOT)}")
        return False
    path.write_text(text, encoding="utf-8", newline="\n")
    print(f"generated   {path.relative_to(ROOT)}")
    return True
